### ISSUE TITLE
Unknown environment 

### ISSUE THREAD

**Issue by wodinga** [simias/psx-guide#5]
I'm trying to render this in an online LaTeX editor but I keep getting "Unknown Environment 'lslisting' and a few other errors

**Comment by simias** [comment]
Glad to see that some people are still interesting in this doc even though I haven't updated it in a while!

I personally use a texlive distribution and simply use the Makefile provided to build the guide.

If you just want a copy of the rendered manual I just uploaded one here: https://svkt.org/~simias/rustation/guide.pdf

If you really want to be able to build the guide in your online editor you'll have to give me more infos, but keep in mind I'm quite a novice when it comes to LaTeX so I might not be able to help very much...

**Comment by wodinga** [comment]
Wow thanks for getting back to me so soon! Yeah I think you have the only guide (at least that I can see) about PSX emulation. I've been wanting to get into emulation for a little while now. The PDF is exactly what I needed. Thanks!

**Comment by simias** [comment]
Cool, don't hesitate to let me know if you have any remarks!
