### ISSUE TITLE
DMA Transfer direction field bad

### ISSUE THREAD

**Issue by yanmingsohu** [simias/psx-guide#9]
"DMA Channel Control register"

Field bits | Description 
0             | Transfer direction: RAM-to-device(0) or device-to-RAM(1)

Fixed: 
0: device-to-RAM
1: RAM-to-device

Is this the case?

**Comment by catphish** [comment]
I believe you are correct. From Nocash specs:

>   0       Transfer Direction    (0=To Main RAM, 1=From Main RAM)
